services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile_backend
    ports:
      - "8080:8080"
    env_file:
      - .env

  frontend:
    build:
      context: .
      dockerfile: Dockerfile_frontend
    ports:
      - "3000:4173"
    depends_on:
      - backend
